/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BehaviorEntry = IDL.Record({
  'date' : IDL.Text,
  'description' : IDL.Text,
  'consequence' : IDL.Opt(IDL.Text),
});
export const BehaviorEntryType = IDL.Variant({
  'incident' : IDL.Null,
  'praise' : IDL.Null,
});
export const BehaviorCategory = IDL.Variant({
  'safety' : IDL.Null,
  'social' : IDL.Null,
  'other' : IDL.Null,
  'academic' : IDL.Null,
  'respect' : IDL.Null,
  'responsibility' : IDL.Null,
});
export const BehaviorSeverity = IDL.Variant({
  'major' : IDL.Null,
  'minor' : IDL.Null,
  'moderate' : IDL.Null,
});
export const ContactMethod = IDL.Variant({
  'either' : IDL.Null,
  'email' : IDL.Null,
  'phone' : IDL.Null,
});
export const GuardianContact = IDL.Record({
  'id' : IDL.Nat,
  'languagePreference' : IDL.Text,
  'relationship' : IDL.Text,
  'emergencyContact' : IDL.Bool,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'preferredContactMethod' : ContactMethod,
  'firstName' : IDL.Text,
});
export const Accommodation = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
});
export const AttendanceStatus = IDL.Variant({
  'tardy' : IDL.Null,
  'present' : IDL.Null,
  'absent' : IDL.Null,
  'excused' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'status' : AttendanceStatus,
  'date' : IDL.Text,
  'reason' : IDL.Opt(IDL.Text),
});
export const SENGoalStatus = IDL.Variant({
  'met' : IDL.Null,
  'notStarted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const SENGoal = IDL.Record({
  'id' : IDL.Nat,
  'status' : SENGoalStatus,
  'description' : IDL.Text,
  'targetDate' : IDL.Text,
});
export const SENPlanType = IDL.Variant({
  'iep' : IDL.Null,
  'sen' : IDL.Null,
  'other' : IDL.Null,
  'none' : IDL.Null,
  'plan504' : IDL.Null,
});
export const SENPlan = IDL.Record({
  'expiryDate' : IDL.Text,
  'reviewDate' : IDL.Text,
  'goals' : IDL.Vec(SENGoal),
  'notes' : IDL.Text,
  'services' : IDL.Vec(IDL.Text),
  'planType' : SENPlanType,
  'coordinator' : IDL.Text,
  'startDate' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BehaviorLog = IDL.Record({
  'context' : IDL.Text,
  'entryType' : BehaviorEntryType,
  'followUpNeeded' : IDL.Bool,
  'studentName' : IDL.Text,
  'description' : IDL.Text,
  'entryId' : IDL.Nat,
  'category' : BehaviorCategory,
  'severity' : IDL.Opt(BehaviorSeverity),
  'actionTaken' : IDL.Opt(IDL.Text),
  'loggedAt' : Time,
});
export const Student = IDL.Record({
  'familyName' : IDL.Text,
  'studentId' : IDL.Text,
  'guardianContacts' : IDL.Vec(GuardianContact),
  'createdAt' : Time,
  'attendanceRecords' : IDL.Vec(AttendanceRecord),
  'teacherNotes' : IDL.Text,
  'behaviorEntries' : IDL.Vec(BehaviorEntry),
  'senPlan' : IDL.Opt(SENPlan),
  'accommodations' : IDL.Vec(Accommodation),
  'gradeLevel' : IDL.Text,
  'preferredName' : IDL.Opt(IDL.Text),
  'medicalNotes' : IDL.Text,
  'photo' : IDL.Text,
  'givenNames' : IDL.Text,
  'interventionPlans' : IDL.Text,
  'allergies' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBehaviorEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [BehaviorEntry],
      [],
    ),
  'addBehaviorLog' : IDL.Func(
      [
        IDL.Text,
        BehaviorEntryType,
        BehaviorCategory,
        IDL.Text,
        IDL.Text,
        IDL.Opt(BehaviorSeverity),
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'addGuardianContact' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ContactMethod,
        IDL.Text,
        IDL.Bool,
      ],
      [GuardianContact],
      [],
    ),
  'addStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Vec(Accommodation),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(AttendanceRecord),
        IDL.Vec(GuardianContact),
        IDL.Text,
        IDL.Text,
        IDL.Vec(BehaviorEntry),
        IDL.Opt(SENPlan),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBehaviorEntry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteBehaviorLog' : IDL.Func([IDL.Nat], [], []),
  'deleteGuardianContact' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'getAccommodationsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Accommodation)],
      ['query'],
    ),
  'getAllBehaviorLogs' : IDL.Func([], [IDL.Vec(BehaviorLog)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getBehaviorEntriesByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BehaviorEntry)],
      ['query'],
    ),
  'getBehaviorLogById' : IDL.Func([IDL.Nat], [IDL.Opt(BehaviorLog)], ['query']),
  'getBehaviorLogsByCategory' : IDL.Func(
      [BehaviorCategory],
      [IDL.Vec(BehaviorLog)],
      ['query'],
    ),
  'getBehaviorLogsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BehaviorLog)],
      ['query'],
    ),
  'getBehaviorLogsByType' : IDL.Func(
      [BehaviorEntryType],
      [IDL.Vec(BehaviorLog)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGuardiansByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GuardianContact)],
      ['query'],
    ),
  'getRoster' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSENPlan' : IDL.Func([IDL.Text], [IDL.Opt(SENPlan)], ['query']),
  'getStudentById' : IDL.Func([IDL.Text], [Student], ['query']),
  'getStudentCountByClass' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getStudentsByClass' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedStudents' : IDL.Func([], [], []),
  'updateBehaviorEntry' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [BehaviorEntry],
      [],
    ),
  'updateBehaviorLog' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        BehaviorEntryType,
        BehaviorCategory,
        IDL.Text,
        IDL.Text,
        IDL.Opt(BehaviorSeverity),
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateGuardianContact' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ContactMethod,
        IDL.Text,
        IDL.Bool,
      ],
      [GuardianContact],
      [],
    ),
  'updateSENPlan' : IDL.Func([IDL.Text, SENPlan], [], []),
  'updateStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Vec(Accommodation),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(AttendanceRecord),
        IDL.Vec(GuardianContact),
        IDL.Text,
        IDL.Text,
        IDL.Vec(BehaviorEntry),
        IDL.Opt(SENPlan),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BehaviorEntry = IDL.Record({
    'date' : IDL.Text,
    'description' : IDL.Text,
    'consequence' : IDL.Opt(IDL.Text),
  });
  const BehaviorEntryType = IDL.Variant({
    'incident' : IDL.Null,
    'praise' : IDL.Null,
  });
  const BehaviorCategory = IDL.Variant({
    'safety' : IDL.Null,
    'social' : IDL.Null,
    'other' : IDL.Null,
    'academic' : IDL.Null,
    'respect' : IDL.Null,
    'responsibility' : IDL.Null,
  });
  const BehaviorSeverity = IDL.Variant({
    'major' : IDL.Null,
    'minor' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const ContactMethod = IDL.Variant({
    'either' : IDL.Null,
    'email' : IDL.Null,
    'phone' : IDL.Null,
  });
  const GuardianContact = IDL.Record({
    'id' : IDL.Nat,
    'languagePreference' : IDL.Text,
    'relationship' : IDL.Text,
    'emergencyContact' : IDL.Bool,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'preferredContactMethod' : ContactMethod,
    'firstName' : IDL.Text,
  });
  const Accommodation = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
  });
  const AttendanceStatus = IDL.Variant({
    'tardy' : IDL.Null,
    'present' : IDL.Null,
    'absent' : IDL.Null,
    'excused' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'status' : AttendanceStatus,
    'date' : IDL.Text,
    'reason' : IDL.Opt(IDL.Text),
  });
  const SENGoalStatus = IDL.Variant({
    'met' : IDL.Null,
    'notStarted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const SENGoal = IDL.Record({
    'id' : IDL.Nat,
    'status' : SENGoalStatus,
    'description' : IDL.Text,
    'targetDate' : IDL.Text,
  });
  const SENPlanType = IDL.Variant({
    'iep' : IDL.Null,
    'sen' : IDL.Null,
    'other' : IDL.Null,
    'none' : IDL.Null,
    'plan504' : IDL.Null,
  });
  const SENPlan = IDL.Record({
    'expiryDate' : IDL.Text,
    'reviewDate' : IDL.Text,
    'goals' : IDL.Vec(SENGoal),
    'notes' : IDL.Text,
    'services' : IDL.Vec(IDL.Text),
    'planType' : SENPlanType,
    'coordinator' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BehaviorLog = IDL.Record({
    'context' : IDL.Text,
    'entryType' : BehaviorEntryType,
    'followUpNeeded' : IDL.Bool,
    'studentName' : IDL.Text,
    'description' : IDL.Text,
    'entryId' : IDL.Nat,
    'category' : BehaviorCategory,
    'severity' : IDL.Opt(BehaviorSeverity),
    'actionTaken' : IDL.Opt(IDL.Text),
    'loggedAt' : Time,
  });
  const Student = IDL.Record({
    'familyName' : IDL.Text,
    'studentId' : IDL.Text,
    'guardianContacts' : IDL.Vec(GuardianContact),
    'createdAt' : Time,
    'attendanceRecords' : IDL.Vec(AttendanceRecord),
    'teacherNotes' : IDL.Text,
    'behaviorEntries' : IDL.Vec(BehaviorEntry),
    'senPlan' : IDL.Opt(SENPlan),
    'accommodations' : IDL.Vec(Accommodation),
    'gradeLevel' : IDL.Text,
    'preferredName' : IDL.Opt(IDL.Text),
    'medicalNotes' : IDL.Text,
    'photo' : IDL.Text,
    'givenNames' : IDL.Text,
    'interventionPlans' : IDL.Text,
    'allergies' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBehaviorEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [BehaviorEntry],
        [],
      ),
    'addBehaviorLog' : IDL.Func(
        [
          IDL.Text,
          BehaviorEntryType,
          BehaviorCategory,
          IDL.Text,
          IDL.Text,
          IDL.Opt(BehaviorSeverity),
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'addGuardianContact' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ContactMethod,
          IDL.Text,
          IDL.Bool,
        ],
        [GuardianContact],
        [],
      ),
    'addStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Vec(Accommodation),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(AttendanceRecord),
          IDL.Vec(GuardianContact),
          IDL.Text,
          IDL.Text,
          IDL.Vec(BehaviorEntry),
          IDL.Opt(SENPlan),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBehaviorEntry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteBehaviorLog' : IDL.Func([IDL.Nat], [], []),
    'deleteGuardianContact' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'getAccommodationsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Accommodation)],
        ['query'],
      ),
    'getAllBehaviorLogs' : IDL.Func([], [IDL.Vec(BehaviorLog)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getBehaviorEntriesByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BehaviorEntry)],
        ['query'],
      ),
    'getBehaviorLogById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BehaviorLog)],
        ['query'],
      ),
    'getBehaviorLogsByCategory' : IDL.Func(
        [BehaviorCategory],
        [IDL.Vec(BehaviorLog)],
        ['query'],
      ),
    'getBehaviorLogsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BehaviorLog)],
        ['query'],
      ),
    'getBehaviorLogsByType' : IDL.Func(
        [BehaviorEntryType],
        [IDL.Vec(BehaviorLog)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGuardiansByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GuardianContact)],
        ['query'],
      ),
    'getRoster' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSENPlan' : IDL.Func([IDL.Text], [IDL.Opt(SENPlan)], ['query']),
    'getStudentById' : IDL.Func([IDL.Text], [Student], ['query']),
    'getStudentCountByClass' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getStudentsByClass' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedStudents' : IDL.Func([], [], []),
    'updateBehaviorEntry' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [BehaviorEntry],
        [],
      ),
    'updateBehaviorLog' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          BehaviorEntryType,
          BehaviorCategory,
          IDL.Text,
          IDL.Text,
          IDL.Opt(BehaviorSeverity),
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateGuardianContact' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ContactMethod,
          IDL.Text,
          IDL.Bool,
        ],
        [GuardianContact],
        [],
      ),
    'updateSENPlan' : IDL.Func([IDL.Text, SENPlan], [], []),
    'updateStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Vec(Accommodation),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(AttendanceRecord),
          IDL.Vec(GuardianContact),
          IDL.Text,
          IDL.Text,
          IDL.Vec(BehaviorEntry),
          IDL.Opt(SENPlan),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };