/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Accommodation { 'id' : bigint, 'description' : string }
export interface AttendanceRecord {
  'status' : AttendanceStatus,
  'date' : string,
  'reason' : [] | [string],
}
export type AttendanceStatus = { 'tardy' : null } |
  { 'present' : null } |
  { 'absent' : null } |
  { 'excused' : null };
export type BehaviorCategory = { 'safety' : null } |
  { 'social' : null } |
  { 'other' : null } |
  { 'academic' : null } |
  { 'respect' : null } |
  { 'responsibility' : null };
export interface BehaviorEntry {
  'date' : string,
  'description' : string,
  'consequence' : [] | [string],
}
export type BehaviorEntryType = { 'incident' : null } |
  { 'praise' : null };
export interface BehaviorLog {
  'context' : string,
  'entryType' : BehaviorEntryType,
  'followUpNeeded' : boolean,
  'studentName' : string,
  'description' : string,
  'entryId' : bigint,
  'category' : BehaviorCategory,
  'severity' : [] | [BehaviorSeverity],
  'actionTaken' : [] | [string],
  'loggedAt' : Time,
}
export type BehaviorSeverity = { 'major' : null } |
  { 'minor' : null } |
  { 'moderate' : null };
export type ContactMethod = { 'either' : null } |
  { 'email' : null } |
  { 'phone' : null };
export interface GuardianContact {
  'id' : bigint,
  'languagePreference' : string,
  'relationship' : string,
  'emergencyContact' : boolean,
  'email' : string,
  'phone' : string,
  'lastName' : string,
  'preferredContactMethod' : ContactMethod,
  'firstName' : string,
}
export interface SENGoal {
  'id' : bigint,
  'status' : SENGoalStatus,
  'description' : string,
  'targetDate' : string,
}
export type SENGoalStatus = { 'met' : null } |
  { 'notStarted' : null } |
  { 'inProgress' : null };
export interface SENPlan {
  'expiryDate' : string,
  'reviewDate' : string,
  'goals' : Array<SENGoal>,
  'notes' : string,
  'services' : Array<string>,
  'planType' : SENPlanType,
  'coordinator' : string,
  'startDate' : string,
}
export type SENPlanType = { 'iep' : null } |
  { 'sen' : null } |
  { 'other' : null } |
  { 'none' : null } |
  { 'plan504' : null };
export interface Student {
  'familyName' : string,
  'studentId' : string,
  'guardianContacts' : Array<GuardianContact>,
  'createdAt' : Time,
  'attendanceRecords' : Array<AttendanceRecord>,
  'teacherNotes' : string,
  'behaviorEntries' : Array<BehaviorEntry>,
  'senPlan' : [] | [SENPlan],
  'accommodations' : Array<Accommodation>,
  'gradeLevel' : string,
  'preferredName' : [] | [string],
  'medicalNotes' : string,
  'photo' : string,
  'givenNames' : string,
  'interventionPlans' : string,
  'allergies' : Array<string>,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBehaviorEntry' : ActorMethod<
    [string, string, string, [] | [string]],
    BehaviorEntry
  >,
  'addBehaviorLog' : ActorMethod<
    [
      string,
      BehaviorEntryType,
      BehaviorCategory,
      string,
      string,
      [] | [BehaviorSeverity],
      [] | [string],
      boolean,
    ],
    bigint
  >,
  'addGuardianContact' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      ContactMethod,
      string,
      boolean,
    ],
    GuardianContact
  >,
  'addStudent' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      Array<Accommodation>,
      Array<string>,
      string,
      Array<AttendanceRecord>,
      Array<GuardianContact>,
      string,
      string,
      Array<BehaviorEntry>,
      [] | [SENPlan],
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBehaviorEntry' : ActorMethod<[string, bigint], undefined>,
  'deleteBehaviorLog' : ActorMethod<[bigint], undefined>,
  'deleteGuardianContact' : ActorMethod<[string, bigint], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'getAccommodationsByStudent' : ActorMethod<[string], Array<Accommodation>>,
  'getAllBehaviorLogs' : ActorMethod<[], Array<BehaviorLog>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getBehaviorEntriesByStudent' : ActorMethod<[string], Array<BehaviorEntry>>,
  'getBehaviorLogById' : ActorMethod<[bigint], [] | [BehaviorLog]>,
  'getBehaviorLogsByCategory' : ActorMethod<
    [BehaviorCategory],
    Array<BehaviorLog>
  >,
  'getBehaviorLogsByStudent' : ActorMethod<[string], Array<BehaviorLog>>,
  'getBehaviorLogsByType' : ActorMethod<
    [BehaviorEntryType],
    Array<BehaviorLog>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGuardiansByStudent' : ActorMethod<[string], Array<GuardianContact>>,
  'getRoster' : ActorMethod<[], Array<string>>,
  'getSENPlan' : ActorMethod<[string], [] | [SENPlan]>,
  'getStudentById' : ActorMethod<[string], Student>,
  'getStudentCountByClass' : ActorMethod<[string], bigint>,
  'getStudentsByClass' : ActorMethod<[string], Array<Student>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedStudents' : ActorMethod<[], undefined>,
  'updateBehaviorEntry' : ActorMethod<
    [string, bigint, string, string, [] | [string]],
    BehaviorEntry
  >,
  'updateBehaviorLog' : ActorMethod<
    [
      bigint,
      string,
      BehaviorEntryType,
      BehaviorCategory,
      string,
      string,
      [] | [BehaviorSeverity],
      [] | [string],
      boolean,
    ],
    undefined
  >,
  'updateGuardianContact' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      ContactMethod,
      string,
      boolean,
    ],
    GuardianContact
  >,
  'updateSENPlan' : ActorMethod<[string, SENPlan], undefined>,
  'updateStudent' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      Array<Accommodation>,
      Array<string>,
      string,
      Array<AttendanceRecord>,
      Array<GuardianContact>,
      string,
      string,
      Array<BehaviorEntry>,
      [] | [SENPlan],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];