/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Student {
    familyName: string;
    studentId: string;
    guardianContacts: Array<GuardianContact>;
    createdAt: Time;
    attendanceRecords: Array<AttendanceRecord>;
    teacherNotes: string;
    behaviorEntries: Array<BehaviorEntry>;
    senPlan?: SENPlan;
    accommodations: Array<Accommodation>;
    gradeLevel: string;
    preferredName?: string;
    medicalNotes: string;
    photo: string;
    givenNames: string;
    interventionPlans: string;
    allergies: Array<string>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SENGoal {
    id: bigint;
    status: SENGoalStatus;
    description: string;
    targetDate: string;
}
export interface GuardianContact {
    id: bigint;
    languagePreference: string;
    relationship: string;
    emergencyContact: boolean;
    email: string;
    phone: string;
    lastName: string;
    preferredContactMethod: ContactMethod;
    firstName: string;
}
export interface BehaviorLog {
    context: string;
    entryType: BehaviorEntryType;
    followUpNeeded: boolean;
    studentName: string;
    description: string;
    entryId: bigint;
    category: BehaviorCategory;
    severity?: BehaviorSeverity;
    actionTaken?: string;
    loggedAt: Time;
}
export interface BehaviorEntry {
    date: string;
    description: string;
    consequence?: string;
}
export interface SENPlan {
    expiryDate: string;
    reviewDate: string;
    goals: Array<SENGoal>;
    notes: string;
    services: Array<string>;
    planType: SENPlanType;
    coordinator: string;
    startDate: string;
}
export interface Accommodation {
    id: bigint;
    description: string;
}
export interface AttendanceRecord {
    status: AttendanceStatus;
    date: string;
    reason?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
}
export enum AttendanceStatus {
    tardy = "tardy",
    present = "present",
    absent = "absent",
    excused = "excused"
}
export enum BehaviorCategory {
    safety = "safety",
    social = "social",
    other = "other",
    academic = "academic",
    respect = "respect",
    responsibility = "responsibility"
}
export enum BehaviorEntryType {
    incident = "incident",
    praise = "praise"
}
export enum BehaviorSeverity {
    major = "major",
    minor = "minor",
    moderate = "moderate"
}
export enum ContactMethod {
    either = "either",
    email = "email",
    phone = "phone"
}
export enum SENGoalStatus {
    met = "met",
    notStarted = "notStarted",
    inProgress = "inProgress"
}
export enum SENPlanType {
    iep = "iep",
    sen = "sen",
    other = "other",
    none = "none",
    plan504 = "plan504"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBehaviorEntry(studentId: string, date: string, description: string, consequence: string | null): Promise<BehaviorEntry>;
    addBehaviorLog(studentName: string, entryType: BehaviorEntryType, category: BehaviorCategory, context: string, description: string, severity: BehaviorSeverity | null, actionTaken: string | null, followUpNeeded: boolean): Promise<bigint>;
    addGuardianContact(studentId: string, firstName: string, lastName: string, relationship: string, phone: string, email: string, preferredContactMethod: ContactMethod, languagePreference: string, emergencyContact: boolean): Promise<GuardianContact>;
    addStudent(studentId: string, givenNames: string, familyName: string, preferredName: string | null, gradeLevel: string, photo: string, accommodations: Array<Accommodation>, allergies: Array<string>, medicalNotes: string, attendanceRecords: Array<AttendanceRecord>, guardianContacts: Array<GuardianContact>, teacherNotes: string, interventionPlans: string, behaviorEntries: Array<BehaviorEntry>, senPlan: SENPlan | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBehaviorEntry(studentId: string, _entryId: bigint): Promise<void>;
    deleteBehaviorLog(entryId: bigint): Promise<void>;
    deleteGuardianContact(studentId: string, contactId: bigint): Promise<void>;
    deleteStudent(studentId: string): Promise<void>;
    getAccommodationsByStudent(studentId: string): Promise<Array<Accommodation>>;
    getAllBehaviorLogs(): Promise<Array<BehaviorLog>>;
    getAllStudents(): Promise<Array<Student>>;
    getBehaviorEntriesByStudent(studentId: string): Promise<Array<BehaviorEntry>>;
    getBehaviorLogById(entryId: bigint): Promise<BehaviorLog | null>;
    getBehaviorLogsByCategory(category: BehaviorCategory): Promise<Array<BehaviorLog>>;
    getBehaviorLogsByStudent(studentName: string): Promise<Array<BehaviorLog>>;
    getBehaviorLogsByType(entryType: BehaviorEntryType): Promise<Array<BehaviorLog>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGuardiansByStudent(studentId: string): Promise<Array<GuardianContact>>;
    getRoster(): Promise<Array<string>>;
    getSENPlan(studentId: string): Promise<SENPlan | null>;
    getStudentById(studentId: string): Promise<Student>;
    getStudentCountByClass(className: string): Promise<bigint>;
    getStudentsByClass(className: string): Promise<Array<Student>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedStudents(): Promise<void>;
    updateBehaviorEntry(studentId: string, entryId: bigint, date: string, description: string, consequence: string | null): Promise<BehaviorEntry>;
    updateBehaviorLog(entryId: bigint, studentName: string, entryType: BehaviorEntryType, category: BehaviorCategory, context: string, description: string, severity: BehaviorSeverity | null, actionTaken: string | null, followUpNeeded: boolean): Promise<void>;
    updateGuardianContact(studentId: string, contactId: bigint, firstName: string, lastName: string, relationship: string, phone: string, email: string, preferredContactMethod: ContactMethod, languagePreference: string, emergencyContact: boolean): Promise<GuardianContact>;
    updateSENPlan(studentId: string, senPlan: SENPlan): Promise<void>;
    updateStudent(studentId: string, givenNames: string, familyName: string, preferredName: string | null, gradeLevel: string, photo: string, accommodations: Array<Accommodation>, allergies: Array<string>, medicalNotes: string, attendanceRecords: Array<AttendanceRecord>, guardianContacts: Array<GuardianContact>, teacherNotes: string, interventionPlans: string, behaviorEntries: Array<BehaviorEntry>, senPlan: SENPlan | null): Promise<void>;
}
import type { Accommodation as _Accommodation, AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, BehaviorCategory as _BehaviorCategory, BehaviorEntry as _BehaviorEntry, BehaviorEntryType as _BehaviorEntryType, BehaviorLog as _BehaviorLog, BehaviorSeverity as _BehaviorSeverity, ContactMethod as _ContactMethod, GuardianContact as _GuardianContact, SENGoal as _SENGoal, SENGoalStatus as _SENGoalStatus, SENPlan as _SENPlan, SENPlanType as _SENPlanType, Student as _Student, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBehaviorEntry(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<BehaviorEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addBehaviorEntry(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
                return from_candid_BehaviorEntry_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBehaviorEntry(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
            return from_candid_BehaviorEntry_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addBehaviorLog(arg0: string, arg1: BehaviorEntryType, arg2: BehaviorCategory, arg3: string, arg4: string, arg5: BehaviorSeverity | null, arg6: string | null, arg7: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBehaviorLog(arg0, to_candid_BehaviorEntryType_n12(this._uploadFile, this._downloadFile, arg1), to_candid_BehaviorCategory_n14(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBehaviorLog(arg0, to_candid_BehaviorEntryType_n12(this._uploadFile, this._downloadFile, arg1), to_candid_BehaviorCategory_n14(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async addGuardianContact(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: ContactMethod, arg7: string, arg8: boolean): Promise<GuardianContact> {
        if (this.processError) {
            try {
                const result = await this.actor.addGuardianContact(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_ContactMethod_n19(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
                return from_candid_GuardianContact_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGuardianContact(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_ContactMethod_n19(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
            return from_candid_GuardianContact_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStudent(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string, arg5: string, arg6: Array<Accommodation>, arg7: Array<string>, arg8: string, arg9: Array<AttendanceRecord>, arg10: Array<GuardianContact>, arg11: string, arg12: string, arg13: Array<BehaviorEntry>, arg14: SENPlan | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, to_candid_vec_n25(this._uploadFile, this._downloadFile, arg9), to_candid_vec_n30(this._uploadFile, this._downloadFile, arg10), arg11, arg12, to_candid_vec_n33(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n36(this._uploadFile, this._downloadFile, arg14));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, to_candid_vec_n25(this._uploadFile, this._downloadFile, arg9), to_candid_vec_n30(this._uploadFile, this._downloadFile, arg10), arg11, arg12, to_candid_vec_n33(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n36(this._uploadFile, this._downloadFile, arg14));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBehaviorEntry(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBehaviorEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBehaviorEntry(arg0, arg1);
            return result;
        }
    }
    async deleteBehaviorLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBehaviorLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBehaviorLog(arg0);
            return result;
        }
    }
    async deleteGuardianContact(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGuardianContact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGuardianContact(arg0, arg1);
            return result;
        }
    }
    async deleteStudent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async getAccommodationsByStudent(arg0: string): Promise<Array<Accommodation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccommodationsByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccommodationsByStudent(arg0);
            return result;
        }
    }
    async getAllBehaviorLogs(): Promise<Array<BehaviorLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBehaviorLogs();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBehaviorLogs();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBehaviorEntriesByStudent(arg0: string): Promise<Array<BehaviorEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBehaviorEntriesByStudent(arg0);
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBehaviorEntriesByStudent(arg0);
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBehaviorLogById(arg0: bigint): Promise<BehaviorLog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBehaviorLogById(arg0);
                return from_candid_opt_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBehaviorLogById(arg0);
            return from_candid_opt_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBehaviorLogsByCategory(arg0: BehaviorCategory): Promise<Array<BehaviorLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBehaviorLogsByCategory(to_candid_BehaviorCategory_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBehaviorLogsByCategory(to_candid_BehaviorCategory_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBehaviorLogsByStudent(arg0: string): Promise<Array<BehaviorLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBehaviorLogsByStudent(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBehaviorLogsByStudent(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBehaviorLogsByType(arg0: BehaviorEntryType): Promise<Array<BehaviorLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBehaviorLogsByType(to_candid_BehaviorEntryType_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBehaviorLogsByType(to_candid_BehaviorEntryType_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuardiansByStudent(arg0: string): Promise<Array<GuardianContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuardiansByStudent(arg0);
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuardiansByStudent(arg0);
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoster(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoster();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoster();
            return result;
        }
    }
    async getSENPlan(arg0: string): Promise<SENPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSENPlan(arg0);
                return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSENPlan(arg0);
            return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentById(arg0: string): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentById(arg0);
                return from_candid_Student_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentById(arg0);
            return from_candid_Student_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentCountByClass(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentCountByClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentCountByClass(arg0);
            return result;
        }
    }
    async getStudentsByClass(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByClass(arg0);
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsByClass(arg0);
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedStudents(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedStudents();
            return result;
        }
    }
    async updateBehaviorEntry(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string | null): Promise<BehaviorEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBehaviorEntry(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return from_candid_BehaviorEntry_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBehaviorEntry(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return from_candid_BehaviorEntry_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBehaviorLog(arg0: bigint, arg1: string, arg2: BehaviorEntryType, arg3: BehaviorCategory, arg4: string, arg5: string, arg6: BehaviorSeverity | null, arg7: string | null, arg8: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBehaviorLog(arg0, arg1, to_candid_BehaviorEntryType_n12(this._uploadFile, this._downloadFile, arg2), to_candid_BehaviorCategory_n14(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBehaviorLog(arg0, arg1, to_candid_BehaviorEntryType_n12(this._uploadFile, this._downloadFile, arg2), to_candid_BehaviorCategory_n14(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), arg8);
            return result;
        }
    }
    async updateGuardianContact(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: ContactMethod, arg8: string, arg9: boolean): Promise<GuardianContact> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGuardianContact(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_ContactMethod_n19(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
                return from_candid_GuardianContact_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGuardianContact(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_ContactMethod_n19(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
            return from_candid_GuardianContact_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSENPlan(arg0: string, arg1: SENPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSENPlan(arg0, to_candid_SENPlan_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSENPlan(arg0, to_candid_SENPlan_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStudent(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string, arg5: string, arg6: Array<Accommodation>, arg7: Array<string>, arg8: string, arg9: Array<AttendanceRecord>, arg10: Array<GuardianContact>, arg11: string, arg12: string, arg13: Array<BehaviorEntry>, arg14: SENPlan | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, to_candid_vec_n25(this._uploadFile, this._downloadFile, arg9), to_candid_vec_n30(this._uploadFile, this._downloadFile, arg10), arg11, arg12, to_candid_vec_n33(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n36(this._uploadFile, this._downloadFile, arg14));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, to_candid_vec_n25(this._uploadFile, this._downloadFile, arg9), to_candid_vec_n30(this._uploadFile, this._downloadFile, arg10), arg11, arg12, to_candid_vec_n33(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n36(this._uploadFile, this._downloadFile, arg14));
            return result;
        }
    }
}
function from_candid_AttendanceRecord_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function from_candid_BehaviorCategory_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BehaviorCategory): BehaviorCategory {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_BehaviorEntryType_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BehaviorEntryType): BehaviorEntryType {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_BehaviorEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BehaviorEntry): BehaviorEntry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_BehaviorLog_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BehaviorLog): BehaviorLog {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_BehaviorSeverity_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BehaviorSeverity): BehaviorSeverity {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_ContactMethod_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactMethod): ContactMethod {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_GuardianContact_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GuardianContact): GuardianContact {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SENGoalStatus_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SENGoalStatus): SENGoalStatus {
    return from_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function from_candid_SENGoal_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SENGoal): SENGoal {
    return from_candid_record_n73(_uploadFile, _downloadFile, value);
}
function from_candid_SENPlanType_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SENPlanType): SENPlanType {
    return from_candid_variant_n77(_uploadFile, _downloadFile, value);
}
function from_candid_SENPlan_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SENPlan): SENPlan {
    return from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n81(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BehaviorSeverity]): BehaviorSeverity | null {
    return value.length === 0 ? null : from_candid_BehaviorSeverity_n56(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SENPlan]): SENPlan | null {
    return value.length === 0 ? null : from_candid_SENPlan_n69(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BehaviorLog]): BehaviorLog | null {
    return value.length === 0 ? null : from_candid_BehaviorLog_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    description: string;
    consequence: [] | [string];
}): {
    date: string;
    description: string;
    consequence?: string;
} {
    return {
        date: value.date,
        description: value.description,
        consequence: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.consequence))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    languagePreference: string;
    relationship: string;
    emergencyContact: boolean;
    email: string;
    phone: string;
    lastName: string;
    preferredContactMethod: _ContactMethod;
    firstName: string;
}): {
    id: bigint;
    languagePreference: string;
    relationship: string;
    emergencyContact: boolean;
    email: string;
    phone: string;
    lastName: string;
    preferredContactMethod: ContactMethod;
    firstName: string;
} {
    return {
        id: value.id,
        languagePreference: value.languagePreference,
        relationship: value.relationship,
        emergencyContact: value.emergencyContact,
        email: value.email,
        phone: value.phone,
        lastName: value.lastName,
        preferredContactMethod: from_candid_ContactMethod_n23(_uploadFile, _downloadFile, value.preferredContactMethod),
        firstName: value.firstName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    context: string;
    entryType: _BehaviorEntryType;
    followUpNeeded: boolean;
    studentName: string;
    description: string;
    entryId: bigint;
    category: _BehaviorCategory;
    severity: [] | [_BehaviorSeverity];
    actionTaken: [] | [string];
    loggedAt: _Time;
}): {
    context: string;
    entryType: BehaviorEntryType;
    followUpNeeded: boolean;
    studentName: string;
    description: string;
    entryId: bigint;
    category: BehaviorCategory;
    severity?: BehaviorSeverity;
    actionTaken?: string;
    loggedAt: Time;
} {
    return {
        context: value.context,
        entryType: from_candid_BehaviorEntryType_n51(_uploadFile, _downloadFile, value.entryType),
        followUpNeeded: value.followUpNeeded,
        studentName: value.studentName,
        description: value.description,
        entryId: value.entryId,
        category: from_candid_BehaviorCategory_n53(_uploadFile, _downloadFile, value.category),
        severity: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.severity)),
        actionTaken: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.actionTaken)),
        loggedAt: value.loggedAt
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    familyName: string;
    studentId: string;
    guardianContacts: Array<_GuardianContact>;
    createdAt: _Time;
    attendanceRecords: Array<_AttendanceRecord>;
    teacherNotes: string;
    behaviorEntries: Array<_BehaviorEntry>;
    senPlan: [] | [_SENPlan];
    accommodations: Array<_Accommodation>;
    gradeLevel: string;
    preferredName: [] | [string];
    medicalNotes: string;
    photo: string;
    givenNames: string;
    interventionPlans: string;
    allergies: Array<string>;
}): {
    familyName: string;
    studentId: string;
    guardianContacts: Array<GuardianContact>;
    createdAt: Time;
    attendanceRecords: Array<AttendanceRecord>;
    teacherNotes: string;
    behaviorEntries: Array<BehaviorEntry>;
    senPlan?: SENPlan;
    accommodations: Array<Accommodation>;
    gradeLevel: string;
    preferredName?: string;
    medicalNotes: string;
    photo: string;
    givenNames: string;
    interventionPlans: string;
    allergies: Array<string>;
} {
    return {
        familyName: value.familyName,
        studentId: value.studentId,
        guardianContacts: from_candid_vec_n61(_uploadFile, _downloadFile, value.guardianContacts),
        createdAt: value.createdAt,
        attendanceRecords: from_candid_vec_n62(_uploadFile, _downloadFile, value.attendanceRecords),
        teacherNotes: value.teacherNotes,
        behaviorEntries: from_candid_vec_n67(_uploadFile, _downloadFile, value.behaviorEntries),
        senPlan: record_opt_to_undefined(from_candid_opt_n68(_uploadFile, _downloadFile, value.senPlan)),
        accommodations: value.accommodations,
        gradeLevel: value.gradeLevel,
        preferredName: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.preferredName)),
        medicalNotes: value.medicalNotes,
        photo: value.photo,
        givenNames: value.givenNames,
        interventionPlans: value.interventionPlans,
        allergies: value.allergies
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AttendanceStatus;
    date: string;
    reason: [] | [string];
}): {
    status: AttendanceStatus;
    date: string;
    reason?: string;
} {
    return {
        status: from_candid_AttendanceStatus_n65(_uploadFile, _downloadFile, value.status),
        date: value.date,
        reason: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.reason))
    };
}
function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiryDate: string;
    reviewDate: string;
    goals: Array<_SENGoal>;
    notes: string;
    services: Array<string>;
    planType: _SENPlanType;
    coordinator: string;
    startDate: string;
}): {
    expiryDate: string;
    reviewDate: string;
    goals: Array<SENGoal>;
    notes: string;
    services: Array<string>;
    planType: SENPlanType;
    coordinator: string;
    startDate: string;
} {
    return {
        expiryDate: value.expiryDate,
        reviewDate: value.reviewDate,
        goals: from_candid_vec_n71(_uploadFile, _downloadFile, value.goals),
        notes: value.notes,
        services: value.services,
        planType: from_candid_SENPlanType_n76(_uploadFile, _downloadFile, value.planType),
        coordinator: value.coordinator,
        startDate: value.startDate
    };
}
function from_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SENGoalStatus;
    description: string;
    targetDate: string;
}): {
    id: bigint;
    status: SENGoalStatus;
    description: string;
    targetDate: string;
} {
    return {
        id: value.id,
        status: from_candid_SENGoalStatus_n74(_uploadFile, _downloadFile, value.status),
        description: value.description,
        targetDate: value.targetDate
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    either: null;
} | {
    email: null;
} | {
    phone: null;
}): ContactMethod {
    return "either" in value ? ContactMethod.either : "email" in value ? ContactMethod.email : "phone" in value ? ContactMethod.phone : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    incident: null;
} | {
    praise: null;
}): BehaviorEntryType {
    return "incident" in value ? BehaviorEntryType.incident : "praise" in value ? BehaviorEntryType.praise : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    safety: null;
} | {
    social: null;
} | {
    other: null;
} | {
    academic: null;
} | {
    respect: null;
} | {
    responsibility: null;
}): BehaviorCategory {
    return "safety" in value ? BehaviorCategory.safety : "social" in value ? BehaviorCategory.social : "other" in value ? BehaviorCategory.other : "academic" in value ? BehaviorCategory.academic : "respect" in value ? BehaviorCategory.respect : "responsibility" in value ? BehaviorCategory.responsibility : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    major: null;
} | {
    minor: null;
} | {
    moderate: null;
}): BehaviorSeverity {
    return "major" in value ? BehaviorSeverity.major : "minor" in value ? BehaviorSeverity.minor : "moderate" in value ? BehaviorSeverity.moderate : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tardy: null;
} | {
    present: null;
} | {
    absent: null;
} | {
    excused: null;
}): AttendanceStatus {
    return "tardy" in value ? AttendanceStatus.tardy : "present" in value ? AttendanceStatus.present : "absent" in value ? AttendanceStatus.absent : "excused" in value ? AttendanceStatus.excused : value;
}
function from_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    met: null;
} | {
    notStarted: null;
} | {
    inProgress: null;
}): SENGoalStatus {
    return "met" in value ? SENGoalStatus.met : "notStarted" in value ? SENGoalStatus.notStarted : "inProgress" in value ? SENGoalStatus.inProgress : value;
}
function from_candid_variant_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    iep: null;
} | {
    sen: null;
} | {
    other: null;
} | {
    none: null;
} | {
    plan504: null;
}): SENPlanType {
    return "iep" in value ? SENPlanType.iep : "sen" in value ? SENPlanType.sen : "other" in value ? SENPlanType.other : "none" in value ? SENPlanType.none : "plan504" in value ? SENPlanType.plan504 : value;
}
function from_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BehaviorLog>): Array<BehaviorLog> {
    return value.map((x)=>from_candid_BehaviorLog_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n59(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GuardianContact>): Array<GuardianContact> {
    return value.map((x)=>from_candid_GuardianContact_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n63(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BehaviorEntry>): Array<BehaviorEntry> {
    return value.map((x)=>from_candid_BehaviorEntry_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SENGoal>): Array<SENGoal> {
    return value.map((x)=>from_candid_SENGoal_n72(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceRecord_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceRecord): _AttendanceRecord {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_BehaviorCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BehaviorCategory): _BehaviorCategory {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_BehaviorEntryType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BehaviorEntryType): _BehaviorEntryType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_BehaviorEntry_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BehaviorEntry): _BehaviorEntry {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_BehaviorSeverity_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BehaviorSeverity): _BehaviorSeverity {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ContactMethod_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactMethod): _ContactMethod {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_GuardianContact_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuardianContact): _GuardianContact {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_SENGoalStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SENGoalStatus): _SENGoalStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_SENGoal_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SENGoal): _SENGoal {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_SENPlanType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SENPlanType): _SENPlanType {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_SENPlan_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SENPlan): _SENPlan {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BehaviorSeverity | null): [] | [_BehaviorSeverity] {
    return value === null ? candid_none() : candid_some(to_candid_BehaviorSeverity_n17(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SENPlan | null): [] | [_SENPlan] {
    return value === null ? candid_none() : candid_some(to_candid_SENPlan_n37(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: AttendanceStatus;
    date: string;
    reason?: string;
}): {
    status: _AttendanceStatus;
    date: string;
    reason: [] | [string];
} {
    return {
        status: to_candid_AttendanceStatus_n28(_uploadFile, _downloadFile, value.status),
        date: value.date,
        reason: value.reason ? candid_some(value.reason) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    languagePreference: string;
    relationship: string;
    emergencyContact: boolean;
    email: string;
    phone: string;
    lastName: string;
    preferredContactMethod: ContactMethod;
    firstName: string;
}): {
    id: bigint;
    languagePreference: string;
    relationship: string;
    emergencyContact: boolean;
    email: string;
    phone: string;
    lastName: string;
    preferredContactMethod: _ContactMethod;
    firstName: string;
} {
    return {
        id: value.id,
        languagePreference: value.languagePreference,
        relationship: value.relationship,
        emergencyContact: value.emergencyContact,
        email: value.email,
        phone: value.phone,
        lastName: value.lastName,
        preferredContactMethod: to_candid_ContactMethod_n19(_uploadFile, _downloadFile, value.preferredContactMethod),
        firstName: value.firstName
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    description: string;
    consequence?: string;
}): {
    date: string;
    description: string;
    consequence: [] | [string];
} {
    return {
        date: value.date,
        description: value.description,
        consequence: value.consequence ? candid_some(value.consequence) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiryDate: string;
    reviewDate: string;
    goals: Array<SENGoal>;
    notes: string;
    services: Array<string>;
    planType: SENPlanType;
    coordinator: string;
    startDate: string;
}): {
    expiryDate: string;
    reviewDate: string;
    goals: Array<_SENGoal>;
    notes: string;
    services: Array<string>;
    planType: _SENPlanType;
    coordinator: string;
    startDate: string;
} {
    return {
        expiryDate: value.expiryDate,
        reviewDate: value.reviewDate,
        goals: to_candid_vec_n39(_uploadFile, _downloadFile, value.goals),
        notes: value.notes,
        services: value.services,
        planType: to_candid_SENPlanType_n44(_uploadFile, _downloadFile, value.planType),
        coordinator: value.coordinator,
        startDate: value.startDate
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: SENGoalStatus;
    description: string;
    targetDate: string;
}): {
    id: bigint;
    status: _SENGoalStatus;
    description: string;
    targetDate: string;
} {
    return {
        id: value.id,
        status: to_candid_SENGoalStatus_n42(_uploadFile, _downloadFile, value.status),
        description: value.description,
        targetDate: value.targetDate
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BehaviorEntryType): {
    incident: null;
} | {
    praise: null;
} {
    return value == BehaviorEntryType.incident ? {
        incident: null
    } : value == BehaviorEntryType.praise ? {
        praise: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BehaviorCategory): {
    safety: null;
} | {
    social: null;
} | {
    other: null;
} | {
    academic: null;
} | {
    respect: null;
} | {
    responsibility: null;
} {
    return value == BehaviorCategory.safety ? {
        safety: null
    } : value == BehaviorCategory.social ? {
        social: null
    } : value == BehaviorCategory.other ? {
        other: null
    } : value == BehaviorCategory.academic ? {
        academic: null
    } : value == BehaviorCategory.respect ? {
        respect: null
    } : value == BehaviorCategory.responsibility ? {
        responsibility: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BehaviorSeverity): {
    major: null;
} | {
    minor: null;
} | {
    moderate: null;
} {
    return value == BehaviorSeverity.major ? {
        major: null
    } : value == BehaviorSeverity.minor ? {
        minor: null
    } : value == BehaviorSeverity.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactMethod): {
    either: null;
} | {
    email: null;
} | {
    phone: null;
} {
    return value == ContactMethod.either ? {
        either: null
    } : value == ContactMethod.email ? {
        email: null
    } : value == ContactMethod.phone ? {
        phone: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    tardy: null;
} | {
    present: null;
} | {
    absent: null;
} | {
    excused: null;
} {
    return value == AttendanceStatus.tardy ? {
        tardy: null
    } : value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value == AttendanceStatus.excused ? {
        excused: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SENGoalStatus): {
    met: null;
} | {
    notStarted: null;
} | {
    inProgress: null;
} {
    return value == SENGoalStatus.met ? {
        met: null
    } : value == SENGoalStatus.notStarted ? {
        notStarted: null
    } : value == SENGoalStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SENPlanType): {
    iep: null;
} | {
    sen: null;
} | {
    other: null;
} | {
    none: null;
} | {
    plan504: null;
} {
    return value == SENPlanType.iep ? {
        iep: null
    } : value == SENPlanType.sen ? {
        sen: null
    } : value == SENPlanType.other ? {
        other: null
    } : value == SENPlanType.none ? {
        none: null
    } : value == SENPlanType.plan504 ? {
        plan504: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AttendanceRecord>): Array<_AttendanceRecord> {
    return value.map((x)=>to_candid_AttendanceRecord_n26(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<GuardianContact>): Array<_GuardianContact> {
    return value.map((x)=>to_candid_GuardianContact_n31(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BehaviorEntry>): Array<_BehaviorEntry> {
    return value.map((x)=>to_candid_BehaviorEntry_n34(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SENGoal>): Array<_SENGoal> {
    return value.map((x)=>to_candid_SENGoal_n40(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
